name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Logowanie do Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: your_dockerhub_username/your_image_name:latest

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumes requirements.txt is in your repo

    - name: Install tmux
      run: |
        sudo apt-get update
        sudo apt-get install -y tmux

    - name: Run Flask Application in tmux
      run: |
        tmux new-session -d -s flask_app 'python main.py'  # Assumes app.py is your Flask app

    - name: Predict from CSV
      run: |
        # Upload CSV file for prediction
        curl -F 'file=@/path/to/CollegeDistance.csv' http://localhost:5000/predict
      shell: bash

    - name: Read and Display Prediction Result
      run: |
        cat prediction_result.txt  # Assuming the Flask app writes to this file
